#!/usr/bin/env bash
result=""
output=$(echo $1 | sed "s/[-_ \*]/\n/g")
for addr in $output
do
    new=${addr:0:1}
    result+=${new[0]^}
    # for new in $addr
    # do
    #     result=${new:0:1}
    #     echo "result is: ${result[0]^}"
    # done
done
echo $result
