#!/usr/bin/env bash

if ! [[ $1 =~ [a-z0-9:] ]] && [[ $1 =~ [?]$ ]]
then
    echo "Calm down, I know what I'm doing!"
elif [[ $1 =~ [?]$ ]] || [[ $1 =~ [?][[:space:]]*$ ]]
then 
    echo "Sure."
elif ! [[ $1 =~ [a-z] ]] && [[ $1 =~ [A-Z] ]]
then
    echo "Whoa, chill out!"
elif [[ -z $1 ]] || [[ $1 =~ ^[[:space:]]*$ ]] || [[ $1 =~ ^['\'t]*$ ]]
then
    echo "Fine. Be that way!"
else
    echo "Whatever."
fi
