#!/bin/bash

num="$1"

if [ "${num}" = "total" ];then
   sum=0
   for i in $(seq 1 64)
   do
     sum=$(echo "2^($i - 1)+$sum" |bc)
   done
   echo $sum
elif [ "$num" -gt 64 ]; then
   echo 'Error: invalid input'
   exit 1
elif [ "$num" -lt 1 ];then
   echo 'Error: invalid input'
   exit 1
else
   echo "2^(${num} - 1)" |bc
fi
