#!/usr/bin/env bash
a=$1
b=$2
count=${#a}
if (( $# != 2 )); then
  echo "Usage: $0 <string1> <string2>"
  exit 1
fi
if (( ${#a} != ${#b} )) 
then
    echo "strands must be of equal length"
    exit 1
else
    distance=0
    for ((i=0;i<count;i++))
    do
        if [[ "${a:i:1}" != "${b:i:1}" ]]
        then
            (( distance++ ))
        fi
    done
fi
echo $distance

