#!/usr/bin/env bash
string="$1"
result=${string,,}
filter_string=$(echo $result | sed -e 's/[- ]//g' | tr -d '')

result1=$(echo "$filter_string" | fold -w1 | sort | uniq | wc -l)

result2=$(echo "$filter_string" | fold -w1 | wc -l)
if [[ ${result1} -eq ${result2} ]]; then
    echo "true"
else
    echo "false"
fi
