#!/usr/bin/env bash
a=$1
if [[ "$a" =~ ^[0-9]*[.][0-9]*$ ]] || [[ "$a" =~ ^[a-zA-Z] ]] || (( $# != 1 ))
then
    echo "Usage: leap.sh <year>"
    exit 1
elif (( $a%400 == 0 )) || (( $a%100 != 0  && $a%4 == 0 ))
then
    echo true
else
    echo false
fi

