#!/usr/bin/env bash
input=$1
validation="^1?[2-9][0-9]{2}[2-9][0-9]{6}$"
result=${input//[!0-9]/}
if [[ $result =~ $validation ]]
then
    echo "${result#1}"
else
    echo "Invalid number.  [1]NXX-NXX-XXXX N=2-9, X=0-9"
    exit 1
fi
