#!/usr/bin/env bash

# (($# == 1)) || { echo "Usage: prime_factor <num>"; exit 1; }
input=$1
i=2
output=()
while (( i <= input))
do
    while((input % i == 0))
    do
        output+=($i)
        (( input /= i))
    done
    (( i== 2 )) && (( i++)) || ((i+=2))
done
echo "${output[@]}"
