#!/usr/bin/env bash

if (($1%105==0))
then
    echo "PlingPlangPlong"
    
elif (($1%15==0))
then
    echo "PlingPlang"
    
elif (($1%21==0))
then
    echo "PlingPlong"
    
elif (($1%35==0))
then
    echo "PlangPlong"
    
elif (($1%3==0))
then
        echo "Pling"
        
elif (($1%5==0))
then
        echo "Plang"
        
elif (($1%7==0))
then
        echo "Plong"
else
        echo $1
fi
