#!/usr/bin/env bash

declare -A colors=(
["black"]=0
["brown"]=1
["red"]=2
["orange"]=3
["yellow"]=4
["green"]=5
["blue"]=6
["violet"]=7
["grey"]=8
["white"]=9
)
if [[ -n ${colors[$1]} && ${colors[$2]} ]]; then    
    echo $(( ${colors[$1]} * 10 + ${colors[$2]} ))
else
    echo "invalid color"
    exit 1
fi
