#!/usr/bin/env bash
series=$1
length=$2
st_len=${#series}
list=()
# echo $st_len

if [[ -z "$series" ]]
then
    echo "series cannot be empty"
    exit 1
    
elif (( $length > $st_len ))
then
    echo "slice length cannot be greater than series length"
    exit 1

elif (( $length == 0 ))
then
    echo "slice length cannot be zero"
    exit 1
    
elif (( $length < 0 ))
then
    echo "slice length cannot be negative"
    exit 1

fi
for ((i=0; i <= st_len - length; i++))
do
    new="${series:i:length}"
    list+=("$new")
done
echo "${list[@]}"
